// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcwteutrmvcpefawntwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjd3RldXRybXZjcGVmYXdudHdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjU5NDgsImV4cCI6MjA2OTA0MTk0OH0.O_Eb7qSS_24UwVFo4G7qYtXeMK8FcQgDJQwDcHQfm-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});